### ISSUE TITLE
No module named 'libyana'

### ISSUE THREAD

**Issue by lixingyewull** [amathislab/HOISDF#8]
Traceback (most recent call last):
  File "/root/HOISDF/main/test.py", line 20, in <module>
    from common.base import Tester
  File "/root/HOISDF/main/../common/base.py", line 19, in <module>
    from data.ho3d import Dataset
  File "/root/HOISDF/main/../data/ho3d.py", line 25, in <module>
    from data import dataset_util, ho3d_util
  File "/root/HOISDF/main/../data/dataset_util.py", line 15, in <module>
    from libyana.meshutils import meshio
ModuleNotFoundError: No module named 'libyana'

**Comment by HaozheQi** [comment]
Hi, thanks for your interest,

Have you tried `pip install git+https://github.com/hassony2/libyana.git`?
